poll_site/poll_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
]

poll_site/polls/urls.py
from django.urls import path

from . import views

app_name="polls"
urlpatterns = [
    # /polls/
    path("", views.index, name="index"),
    # /polls/5/
    path("<int:question_id>/" , views.detail , name = "detail"),
    # /polls/results/5/results
    path("<int:question_id>/results/" , views.results , name="results"),
    # /polls/5/vote/
    path("<int:question_id>/vote/" , views.vote , name="vote")
]

poll_site/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# layout for the database

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def was_published_recently(this):
        return this.pub_date >= timezone.now() - datetime.timedelta(days=1)
    def __str__(this): #I like using 'this', ok?
        return this.question_text

class Choice(models.Model):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(this):
        return this.choice_text

#Remember the 3 step guide to making model changes

## change your models here (models.py)
## run python manage.py makemigrations to apply those changes to the DB
## run pythong manage.py migrate to apply changes to the DB

poll_site/polls/views.py
# View is a 'type' of web page in your django application that generally serves a specific function.

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from .models import Question

def detail(request, question_id):
    question = get_object_or_404(Question , pk=question_id)
    return render(request , "polls/detail.html" , {"question" : question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request , question_id):
    return HttpResponse("You're voting on question %s." % question_id)

def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {
        "latest_question_list" : latest_question_list,
    }
    return render(request , "polls/index.html" , context)

poll_site/polls/templates/polls/detail.html
<style>
    div{
        margin: 0 auto;
    }
</style>

<div>
    <h1> Question: {{ question.question_text }}</h1>
    <h2>Choices:</h2>
    <ul>
        {% for choice in question.choice_set.all %}
            <ul>{{ choice.choice_text }}</ul>
        {% endfor %}
    </ul>
</div>

poll_site/polls/templates/polls/index.html
<style>
    p,ul,a,h1{
        text-align: center;
    }
    div{
        margin: 0 auto;
    }
</style>

<div>
    <h1>Questions</h1>
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <ul><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></ul>
        {% endfor %}
    </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</div>